[package]
name = "strfry-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
futures = "0.3.32"
hex = "0.4.3"
rand = "0.10.1"
rand_chacha = "0.10.0"
secp256k1 = { version = "0.31.1", features = ["rand", "global-context", "hashes"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.11.0"
tokio = { version = "1.52.3", features = ["full"] }
tokio-tungstenite = "0.29.0"
url = "2.5.8"
